# Generated by Django 2.2.2 on 2019-07-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0002_auto_20190719_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='ForumImage'),
        ),
    ]
