# Generated by Django 2.2.2 on 2019-07-21 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websitedata', '0003_auto_20190719_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='Add Description', max_length=100)),
                ('city', models.CharField(blank=True, default='Add your City', max_length=20)),
                ('Website', models.CharField(blank=True, default='Add your Website', max_length=20)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic')),
                ('cover_pic', models.ImageField(blank=True, upload_to='cover_pic')),
                ('user', models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
