# Generated by Django 2.2.2 on 2019-07-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0005_auto_20190721_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, unique=True, upload_to='profile_pic'),
        ),
    ]
