# Generated by Django 2.2.2 on 2019-07-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0006_auto_20190721_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
