# Generated by Django 2.2.2 on 2019-07-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0007_auto_20190721_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pic',
        ),
    ]
