# Generated by Django 2.2.2 on 2019-07-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0008_remove_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic'),
        ),
    ]
