# Generated by Django 2.2.2 on 2019-07-21 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0009_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete='Cascade', to=settings.AUTH_USER_MODEL),
        ),
    ]
