# Generated by Django 2.2.2 on 2019-07-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0010_auto_20190721_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='profile_pic.jpg', upload_to='cover_pic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic.jpg', upload_to='profile_pic'),
        ),
    ]
