# Generated by Django 2.2.2 on 2019-07-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0012_auto_20190721_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pic'),
        ),
    ]
