# Generated by Django 2.2.2 on 2019-07-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedata', '0014_auto_20190721_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
